const TheoryDiscussionsSummary = [
  {
    title: "Porter's 5 Principles",
    description:
      "It is a framework developed by Harvard professor Michael Porter in 1979. It was designed to assess how strong the competitive position of a firm is in the market. The theory is modeled around the assumption that there are 5 forces that determine how intense the competition in any given market is and how attractive entry is."
  },
  {
    title: '3C-1P Approach',
    description:
      "The 3C–1P model defines the first planning step that companies need to take in order to understand their current situation and drive their product. The 3C1P model was proposed by Kenichi Ohmae, a renowned Japanese strategy guru"
  },
  {
    title: '80-20 Rule',
    description:
      "Also known as the Pareto principle, it states that 80% of the outcome comes from just 20% of the total work put in. It is more of an aphorism than a hard and fast scientific rule, but is used to identify the most productive assets of a company. It is most commonly used to point out that 80% of a company's revenue is generated by just 20% of the customers"
  },
  {
    title: 'MECE (Mutually Exclusive Collectively Exhaustive)',
    description:
      "MECE is a principle used by management consulting firms to describe a way of organizing information. The MECE principle suggests that to understand and fix any large problem, you need to understand your options by sorting them into categories that are: Mutually Exclusive– Items can only fit into one category at a time and Collectively Exhaustive – All items can fit into one of the categories"
  }
]

export {TheoryDiscussionsSummary}